{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "42b03c44-dfff-4b03-a06d-431748cbd3c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/data/2023741061/code/Raccoonbot_Openvla/Mujoco\n",
      "-rw-r--r-- 1 root root 19200 May 30 09:06 raccoon_env.py\n"
     ]
    }
   ],
   "source": [
    "!pwd\n",
    "!ls -al raccoon_env.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d77047f2-335f-4570-96ef-bc0cc7e39cc0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[OK] patched: /data/2023741061/code/Raccoonbot_Openvla/Mujoco/raccoon_env.py\n",
      "[OK] backup : /data/2023741061/code/Raccoonbot_Openvla/Mujoco/raccoon_env.py.bak.20260604_104716\n",
      "[OK] helper inserted: True\n",
      "[OK] py_compile passed\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "Rotation-aware 7D-to-4DOF Action Projection with IK-aware Safe Fallback\n",
    "patch script for raccoon_env.py  (Jupyter / plain-python 실행용, heredoc 미사용)\n",
    "\n",
    "동작 방식:\n",
    "  1. AST로 SyncSimRaccoonEnv 클래스와 execute_delta_action7 메서드의 정확한 라인 범위를 찾는다\n",
    "     (텍스트 매칭은 들여쓰기/공백 차이로 깨지기 쉬워 AST 기반으로 위치를 특정한다)\n",
    "  2. execute_delta_action7 본문을 새 구현으로 통째 교체\n",
    "  3. _project_action7_to_raccoon4 helper가 없으면 클래스 본문 끝에 삽입\n",
    "  4. 패치 전 .bak.TIMESTAMP 백업 생성\n",
    "  5. py_compile로 문법 검증\n",
    "\"\"\"\n",
    "import ast\n",
    "import os\n",
    "import shutil\n",
    "import time\n",
    "import py_compile\n",
    "\n",
    "TARGET = \"/data/2023741061/code/Raccoonbot_Openvla/Mujoco/raccoon_env.py\"\n",
    "CLASS_NAME = \"SyncSimRaccoonEnv\"\n",
    "METHOD_NAME = \"execute_delta_action7\"\n",
    "HELPER_NAME = \"_project_action7_to_raccoon4\"\n",
    "\n",
    "\n",
    "# ---- 새 execute_delta_action7 본문 (클래스 들여쓰기 기준 4 spaces) ----\n",
    "NEW_METHOD_SRC = '''\n",
    "    def execute_delta_action7(\n",
    "        self,\n",
    "        action: Sequence[float],\n",
    "        speed: int = 70,\n",
    "        max_delta_xyz: float = 0.01,\n",
    "        delta_scale: float = 1.0,\n",
    "        shrink_ratio: float = 0.15,\n",
    "        max_retries: int = 3,\n",
    "        use_rotation_projection: bool = True,\n",
    "        rot_to_trans: Tuple[float, float, float] = (0.15, 0.10, 0.10),\n",
    "        enable_safe_height_fallback: bool = True,\n",
    "        safe_height_z: float = 0.08,\n",
    "        min_close_height_z: float = 0.035,\n",
    "    ) -> Dict[str, object]:\n",
    "        \"\"\"\n",
    "        OpenVLA 7D delta action -> RaccoonBot 4DOF 실행.\n",
    "\n",
    "        개선점 (Rotation-aware 7D-to-4DOF Projection with IK-aware Safe Fallback):\n",
    "          - use_rotation_projection=True: 회전 성분(droll,dpitch,dyaw)을 폐기하지 않고\n",
    "            작은 Cartesian 보정으로 projection (정책 의도 보존용 heuristic; 운동학적 변환 아님)\n",
    "          - use_rotation_projection=False: 기존 baseline과 정확히 동일 (회전 폐기, 비교 실험용)\n",
    "          - IK 실패 시: shrink retry -> safe-height fallback -> ValueError 순으로 단계적 fallback\n",
    "          - gripper: EE가 너무 높으면 (target_z > min_close_height_z) close를 막고 open 유지\n",
    "\n",
    "        하위호환: 기존 인자는 그대로, optional 인자만 뒤에 추가.\n",
    "        기존 client가 쓰던 key (final_delta_xyz / actual_move_xyz / target_xyz /\n",
    "        gripper_cmd / retry_count) 는 모두 유지.\n",
    "        \"\"\"\n",
    "        if len(action) < 7:\n",
    "            raise ValueError(f\"action 길이가 부족합니다: len={len(action)}, action={action}\")\n",
    "\n",
    "        dx, dy, dz, droll, dpitch, dyaw, gripper = [float(v) for v in action[:7]]\n",
    "        raw_delta_xyz = [dx, dy, dz]\n",
    "        raw_rotation_rpy = [droll, dpitch, dyaw]\n",
    "\n",
    "        # ---- Stage 1: rotation-aware projected delta ----\n",
    "        # helper가 scaling(delta_scale) + rotation projection + clip 까지 모두 처리한다.\n",
    "        proj_dx, proj_dy, proj_dz, projection_info = self._project_action7_to_raccoon4(\n",
    "            dx=dx, dy=dy, dz=dz,\n",
    "            droll=droll, dpitch=dpitch, dyaw=dyaw,\n",
    "            max_delta_xyz=max_delta_xyz,\n",
    "            delta_scale=delta_scale,\n",
    "            use_rotation_projection=use_rotation_projection,\n",
    "            rot_to_trans=rot_to_trans,\n",
    "        )\n",
    "\n",
    "        ee_x, ee_y, ee_z = self.get_ee_pose()\n",
    "\n",
    "        # ---- Stage 2: workspace clipping bounds ----\n",
    "        safe_x_min, safe_x_max = -0.18, 0.18\n",
    "        safe_y_min, safe_y_max = 0.05, 0.20\n",
    "        safe_z_min, safe_z_max = 0.02, 0.11\n",
    "\n",
    "        cur_dx, cur_dy, cur_dz = proj_dx, proj_dy, proj_dz\n",
    "        tried_results = []\n",
    "        chosen_target = None\n",
    "        chosen_delta = None\n",
    "        fallback_used = \"none\"\n",
    "        last_exc = None\n",
    "\n",
    "        # ---- Stage 3+4: IK 시도 + delta shrink retry ----\n",
    "        for retry_idx in range(max_retries + 1):\n",
    "            tx = float(np.clip(ee_x + cur_dx, safe_x_min, safe_x_max))\n",
    "            ty = float(np.clip(ee_y + cur_dy, safe_y_min, safe_y_max))\n",
    "            tz = float(np.clip(ee_z + cur_dz, safe_z_min, safe_z_max))\n",
    "            try:\n",
    "                self.move_to(tx * 100.0, ty * 100.0, tz * 100.0, speed=speed)\n",
    "                chosen_target = (tx, ty, tz)\n",
    "                chosen_delta = (cur_dx, cur_dy, cur_dz)\n",
    "                tried_results.append({\n",
    "                    \"retry_index\": retry_idx, \"stage\": \"shrink_retry\",\n",
    "                    \"delta_xyz\": [cur_dx, cur_dy, cur_dz],\n",
    "                    \"target_xyz\": [tx, ty, tz], \"ok\": True, \"error\": None,\n",
    "                })\n",
    "                break\n",
    "            except Exception as exc:\n",
    "                last_exc = exc\n",
    "                tried_results.append({\n",
    "                    \"retry_index\": retry_idx, \"stage\": \"shrink_retry\",\n",
    "                    \"delta_xyz\": [cur_dx, cur_dy, cur_dz],\n",
    "                    \"target_xyz\": [tx, ty, tz], \"ok\": False, \"error\": str(exc),\n",
    "                })\n",
    "            cur_dx *= (1.0 - shrink_ratio)\n",
    "            cur_dy *= (1.0 - shrink_ratio)\n",
    "            cur_dz *= (1.0 - shrink_ratio)\n",
    "\n",
    "        # ---- Stage 5: safe-height fallback ----\n",
    "        # shrink retry가 전부 실패하면, z를 안전 높이로 올리고 xy 이동 위주로 재시도.\n",
    "        # 낮은 z 에서의 IK 특이점/도달불가를 회피하기 위한 안정화 단계.\n",
    "        if chosen_target is None and enable_safe_height_fallback:\n",
    "            fb_tz = float(np.clip(safe_height_z, safe_z_min, safe_z_max))\n",
    "            # xy는 projected delta의 절반만 적용해 보수적으로 이동\n",
    "            fb_tx = float(np.clip(ee_x + proj_dx * 0.5, safe_x_min, safe_x_max))\n",
    "            fb_ty = float(np.clip(ee_y + proj_dy * 0.5, safe_y_min, safe_y_max))\n",
    "            try:\n",
    "                self.move_to(fb_tx * 100.0, fb_ty * 100.0, fb_tz * 100.0, speed=speed)\n",
    "                chosen_target = (fb_tx, fb_ty, fb_tz)\n",
    "                chosen_delta = (fb_tx - ee_x, fb_ty - ee_y, fb_tz - ee_z)\n",
    "                fallback_used = \"safe_height_xy\"\n",
    "                tried_results.append({\n",
    "                    \"retry_index\": len(tried_results), \"stage\": \"safe_height_fallback\",\n",
    "                    \"delta_xyz\": list(chosen_delta),\n",
    "                    \"target_xyz\": [fb_tx, fb_ty, fb_tz], \"ok\": True, \"error\": None,\n",
    "                })\n",
    "            except Exception as exc:\n",
    "                last_exc = exc\n",
    "                tried_results.append({\n",
    "                    \"retry_index\": len(tried_results), \"stage\": \"safe_height_fallback\",\n",
    "                    \"delta_xyz\": [fb_tx - ee_x, fb_ty - ee_y, fb_tz - ee_z],\n",
    "                    \"target_xyz\": [fb_tx, fb_ty, fb_tz], \"ok\": False, \"error\": str(exc),\n",
    "                })\n",
    "\n",
    "        # ---- Stage 6: 그래도 실패하면 명확한 ValueError ----\n",
    "        if chosen_target is None:\n",
    "            raise ValueError(\n",
    "                f\"IK fail | ee=({ee_x:.4f},{ee_y:.4f},{ee_z:.4f}) | \"\n",
    "                f\"raw_delta=({raw_delta_xyz[0]:.4f},{raw_delta_xyz[1]:.4f},{raw_delta_xyz[2]:.4f}) | \"\n",
    "                f\"projected_delta=({proj_dx:.4f},{proj_dy:.4f},{proj_dz:.4f}) | \"\n",
    "                f\"retries={max_retries} | safe_height_fallback={enable_safe_height_fallback} | \"\n",
    "                f\"last_error={last_exc}\"\n",
    "            )\n",
    "\n",
    "        tx, ty, tz = chosen_target\n",
    "        final_dx, final_dy, final_dz = chosen_delta\n",
    "\n",
    "        # ---- gripper: height-aware close 차단 ----\n",
    "        gripper_blocked_by_height = False\n",
    "        if gripper >= 0.5:\n",
    "            if tz > min_close_height_z:\n",
    "                # 너무 높은 위치에서의 close는 위험/무의미 -> open 유지\n",
    "                self.open_gripper()\n",
    "                gripper_action = \"open\"\n",
    "                gripper_blocked_by_height = True\n",
    "            else:\n",
    "                self.close_gripper()\n",
    "                gripper_action = \"close\"\n",
    "        else:\n",
    "            self.open_gripper()\n",
    "            gripper_action = \"open\"\n",
    "\n",
    "        actual_move = [tx - ee_x, ty - ee_y, tz - ee_z]\n",
    "\n",
    "        return {\n",
    "            \"success\": True,\n",
    "            \"ee_pose_before\": [ee_x, ee_y, ee_z],\n",
    "            \"raw_action\": [float(v) for v in action[:7]],\n",
    "            \"raw_delta_xyz\": raw_delta_xyz,\n",
    "            \"raw_rotation_rpy\": raw_rotation_rpy,\n",
    "            \"applied_delta_xyz\": [proj_dx, proj_dy, proj_dz],\n",
    "            \"final_delta_xyz\": [final_dx, final_dy, final_dz],\n",
    "            \"target_xyz\": [tx, ty, tz],\n",
    "            \"actual_move_xyz\": actual_move,\n",
    "            \"projection_info\": projection_info,\n",
    "            \"fallback_used\": fallback_used,\n",
    "            \"gripper_cmd\": gripper,\n",
    "            \"gripper_action\": gripper_action,\n",
    "            \"gripper_blocked_by_height\": gripper_blocked_by_height,\n",
    "            \"tried_results\": tried_results,\n",
    "            \"retry_count\": len(tried_results) - 1,\n",
    "        }\n",
    "'''\n",
    "\n",
    "# ---- helper method 소스 ----\n",
    "HELPER_SRC = '''\n",
    "    def _project_action7_to_raccoon4(\n",
    "        self,\n",
    "        dx: float, dy: float, dz: float,\n",
    "        droll: float, dpitch: float, dyaw: float,\n",
    "        max_delta_xyz: float,\n",
    "        delta_scale: float,\n",
    "        use_rotation_projection: bool,\n",
    "        rot_to_trans: Tuple[float, float, float],\n",
    "    ):\n",
    "        \"\"\"\n",
    "        OpenVLA 7D delta -> RaccoonBot 실행가능 3D translation delta로 projection.\n",
    "\n",
    "        반환: (proj_dx, proj_dy, proj_dz, projection_info)\n",
    "\n",
    "        처리 순서:\n",
    "          1. translation 성분에 delta_scale 적용  (기존 baseline과 동일하게 유지)\n",
    "          2. use_rotation_projection=True 이면 회전 성분을 작은 Cartesian 보정으로 추가\n",
    "               dx' += alpha * dyaw  * max_delta_xyz\n",
    "               dy' += beta  * droll * max_delta_xyz\n",
    "               dz' += gamma * dpitch* max_delta_xyz\n",
    "             (운동학적 변환이 아니라, 폐기되던 회전 정보를 약하게 보존하는 heuristic)\n",
    "          3. [-max_delta_xyz, max_delta_xyz] 로 clip\n",
    "\n",
    "        use_rotation_projection=False 이면 rotation 보정 = 0 이므로\n",
    "        결과가 기존 baseline (회전 폐기 + scale + clip) 과 정확히 동일하다.\n",
    "        \"\"\"\n",
    "        alpha, beta, gamma = (float(rot_to_trans[0]), float(rot_to_trans[1]), float(rot_to_trans[2]))\n",
    "\n",
    "        # 1. translation scaling\n",
    "        sdx = dx * delta_scale\n",
    "        sdy = dy * delta_scale\n",
    "        sdz = dz * delta_scale\n",
    "\n",
    "        # 2. rotation -> translation 보정\n",
    "        if use_rotation_projection:\n",
    "            rot_dx = alpha * dyaw * max_delta_xyz\n",
    "            rot_dy = beta * droll * max_delta_xyz\n",
    "            rot_dz = gamma * dpitch * max_delta_xyz\n",
    "        else:\n",
    "            rot_dx = rot_dy = rot_dz = 0.0\n",
    "\n",
    "        before_clip = [sdx + rot_dx, sdy + rot_dy, sdz + rot_dz]\n",
    "\n",
    "        # 3. clip\n",
    "        proj_dx = float(np.clip(before_clip[0], -max_delta_xyz, max_delta_xyz))\n",
    "        proj_dy = float(np.clip(before_clip[1], -max_delta_xyz, max_delta_xyz))\n",
    "        proj_dz = float(np.clip(before_clip[2], -max_delta_xyz, max_delta_xyz))\n",
    "\n",
    "        projection_info = {\n",
    "            \"raw_delta_xyz\": [dx, dy, dz],\n",
    "            \"raw_rotation_rpy\": [droll, dpitch, dyaw],\n",
    "            \"scaled_delta_xyz\": [sdx, sdy, sdz],\n",
    "            \"rotation_projection_xyz\": [rot_dx, rot_dy, rot_dz],\n",
    "            \"projected_delta_xyz_before_clip\": list(before_clip),\n",
    "            \"projected_delta_xyz\": [proj_dx, proj_dy, proj_dz],\n",
    "            \"rot_to_trans\": [alpha, beta, gamma],\n",
    "            \"use_rotation_projection\": bool(use_rotation_projection),\n",
    "            \"max_delta_xyz\": float(max_delta_xyz),\n",
    "            \"delta_scale\": float(delta_scale),\n",
    "        }\n",
    "        return proj_dx, proj_dy, proj_dz, projection_info\n",
    "'''\n",
    "\n",
    "\n",
    "def find_class_and_method(tree):\n",
    "    cls = None\n",
    "    for node in tree.body:\n",
    "        if isinstance(node, ast.ClassDef) and node.name == CLASS_NAME:\n",
    "            cls = node\n",
    "            break\n",
    "    if cls is None:\n",
    "        raise RuntimeError(f\"class {CLASS_NAME} 를 찾지 못함\")\n",
    "    method = None\n",
    "    helper_exists = False\n",
    "    for node in cls.body:\n",
    "        if isinstance(node, ast.FunctionDef):\n",
    "            if node.name == METHOD_NAME:\n",
    "                method = node\n",
    "            if node.name == HELPER_NAME:\n",
    "                helper_exists = True\n",
    "    if method is None:\n",
    "        raise RuntimeError(f\"method {METHOD_NAME} 를 찾지 못함\")\n",
    "    return cls, method, helper_exists\n",
    "\n",
    "\n",
    "def main():\n",
    "    if not os.path.exists(TARGET):\n",
    "        raise FileNotFoundError(f\"대상 파일 없음: {TARGET}\")\n",
    "\n",
    "    with open(TARGET, \"r\", encoding=\"utf-8\") as f:\n",
    "        src = f.read()\n",
    "    lines = src.splitlines(keepends=True)\n",
    "\n",
    "    tree = ast.parse(src)\n",
    "    cls, method, helper_exists = find_class_and_method(tree)\n",
    "\n",
    "    # 메서드 라인 범위 (1-indexed). 데코레이터가 있으면 그 시작부터.\n",
    "    m_start = method.lineno\n",
    "    if method.decorator_list:\n",
    "        m_start = min(d.lineno for d in method.decorator_list)\n",
    "    m_end = method.end_lineno  # inclusive\n",
    "\n",
    "    # 백업\n",
    "    ts = time.strftime(\"%Y%m%d_%H%M%S\")\n",
    "    bak = f\"{TARGET}.bak.{ts}\"\n",
    "    shutil.copy2(TARGET, bak)\n",
    "\n",
    "    # 메서드 교체: [m_start-1, m_end) 를 새 본문으로\n",
    "    new_method_lines = NEW_METHOD_SRC.lstrip(\"\\n\").splitlines(keepends=True)\n",
    "    if new_method_lines and not new_method_lines[-1].endswith(\"\\n\"):\n",
    "        new_method_lines[-1] += \"\\n\"\n",
    "\n",
    "    rebuilt = lines[: m_start - 1] + new_method_lines + lines[m_end:]\n",
    "\n",
    "    new_src = \"\".join(rebuilt)\n",
    "\n",
    "    # helper 삽입 (없을 때만): 클래스 끝에 추가\n",
    "    if not helper_exists:\n",
    "        tree2 = ast.parse(new_src)\n",
    "        cls2, _, _ = find_class_and_method(tree2)\n",
    "        cls_end = cls2.end_lineno  # 클래스 마지막 라인 (inclusive)\n",
    "        lines2 = new_src.splitlines(keepends=True)\n",
    "        helper_block = HELPER_SRC.lstrip(\"\\n\")\n",
    "        if not helper_block.endswith(\"\\n\"):\n",
    "            helper_block += \"\\n\"\n",
    "        # 클래스 끝 라인 뒤에 helper 삽입 (앞에 빈 줄 보장)\n",
    "        insert = (\"\\n\" if not lines2[cls_end - 1].endswith(\"\\n\\n\") else \"\") + helper_block\n",
    "        lines2 = lines2[:cls_end] + [insert] + lines2[cls_end:]\n",
    "        new_src = \"\".join(lines2)\n",
    "\n",
    "    with open(TARGET, \"w\", encoding=\"utf-8\") as f:\n",
    "        f.write(new_src)\n",
    "\n",
    "    py_compile.compile(TARGET, doraise=True)\n",
    "    print(f\"[OK] patched: {TARGET}\")\n",
    "    print(f\"[OK] backup : {bak}\")\n",
    "    print(f\"[OK] helper inserted: {not helper_exists}\")\n",
    "    print(f\"[OK] py_compile passed\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e09d291e-5d80-4030-b248-8dae93706afd",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31b08eab-840d-401f-95b6-7647e77f7e38",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
